Add HierarchyRepeater
riganti/dotvvm pull request #1206
Opened 2021-11-05 16:50 UTC by cafour

There is currently no control in the framework able to render recursive hierarchies, so I backported `HierarchyRepeater` from business pack over here.

Implementing any `ItemsControl`, let alone a repeater, is a mine field, so any feedback is very, very welcome.

2021-11-07 12:08 UTC, quigamdev requested changes
We need to rewrite this code to use the standard Item Template mechanism as Repeater uses. 
Tbh we should completely rewrite this control.

2021-11-07 12:59 UTC, cafour commented
@quigamdev

> We need to rewrite this code to use the standard Item Template mechanism as Repeater uses.

What do you mean by standard item template mechanism? This control already uses the same mechanism as Repeater with the exception of the `ResourceManager.AddTemplateResource` method.

This method cannot be used since it generates the template id based from the hash of template's contents... which needs to contain the template id. This can be overcome in two ways: either by rendering the template twice -- once to obtain the id and once to put the id back in, or by generating the template id in some other way (as I did in this PR).

> Tbh we should completely rewrite this control.

This is already pretty much a complete rewrite of `bp:HierarchyRepeater`. I'd rather fix this implementation than start all over again.

2022-04-29 12:45 UTC, exyi approved these changes

2022-04-29 13:05 UTC, quigamdev approved these changes
It looks good to me. I have found just minor issues. 
It would be nice to have also some perf test.

2022-04-29 13:05 UTC, quigamdev commented on src/Samples/Common/Views/ControlSamples/HierarchyRepeater/Basic.dothtml
> +    <dot:HierarchyRepeater DataSource="{value: Empty}"
It would be nice to have a test without ItemTagName and LevelTagName to test that it also works with the placeholder

2022-04-29 13:07 UTC, quigamdev requested changes
I have just noticed, that unit tests are failing.

2022-04-29 13:17 UTC, quigamdev commented on src/Samples/Common/Views/ControlSamples/HierarchyRepeater/Basic.dothtml
> +    <dot:HierarchyRepeater DataSource="{value: Empty}"
Oh, yeah, sorry, my bad.

2022-04-29 13:20 UTC, cafour commented on src/Framework/Framework/Controls/HierarchyRepeater.cs
> +            {
All of them should be removed now.

2022-04-29 13:41 UTC, cafour commented
Limitation: `ItemWrapperCapability` cannot have bindings with a data context set to the item. This limitation is cause by the need to have consistent date context nesting both in client-rendering and server-rendering.

2022-05-01 22:42 UTC, quigamdev approved these changes

2022-05-01 22:42 UTC, merged