Add IHeathCheck implementation to Asp.Net Core hosting
riganti/dotvvm pull request #1209
Opened 2021-11-07 12:43 UTC by exyi

The healthcheck just checks if dotvvm pages can be compiled.

resolves #1205

2021-11-10 11:05 UTC, quigamdev commented
By internal comment from @martindybal we have some glitch there.

2021-11-11 14:11 UTC, martindybal commented
Yes, I reproted it to @exyi on Monday. It's not working when pages are not compile by StatusPage.

2021-11-12 09:41 UTC, cafour requested changes
Could the bug be resolved by keeping the metadata about the compilation (successful or failed) of each markup file in `DefaultControlBuilderFactory` instead of `DotvvmViewCompilationService`?

2021-11-12 09:41 UTC, cafour commented on src/Framework/Hosting.AspNetCore/Hosting/DotvvmHealthCheck.cs
> +            return Task.FromResult(new HealthCheckResult(state, $"Dothtml pages can not be compiled: {views.Take(10).StringJoin(", ")}. See /_dotvvm/diagnostics/compilation for more information."));
The diagnostic page url should not be hardcoded since it can be configured in `DotvvmCompilationPageConfiguration.Url`.

2022-03-23 11:51 UTC, acizmarik approved these changes

2022-03-23 16:05 UTC, cafour approved these changes

2022-04-19 12:13 UTC, merged