Instrument DotVVM with System.Diagnostics.Metrics
riganti/dotvvm pull request #1549
Opened 2023-01-15 21:51 UTC by exyi

The aim is to add prometheus-compatible metrics
to places which can signal a potential problem with
the application (too large VM, compiling too many
bindings or views, ...). The samples project now includes
reference to prometheus-net, so you can go to `/metrics` to see them.

I couldn't find what naming convention should be used for
these .NET metrics, so I used the prometheus conventions
(maybe except label values are in PascalCase, because it's easier that way).
However, prometheus-net seems to have some naming convertor,
which suggest the convention for System.Diagnostics.Metrics
are different (or non-existent...)

2023-01-25 12:24 UTC, acizmarik reviewed
Let's also investigate redirects for static commands. Otherwise looks nice

2023-01-25 12:24 UTC, acizmarik commented on src/Framework/Framework/Hosting/Middlewares/DotvvmLocalResourceMiddleware.cs
> +            var sw = ValueStopwatch.StartNew(isActive: DotvvmMetrics.ResourceServeDuration.Enabled);
We should add a `finally` block to capture also serve failures

2023-01-25 12:24 UTC, acizmarik commented on src/Framework/Framework/Compilation/DefaultControlBuilderFactory.cs
> +                var sw = ValueStopwatch.StartNew();
The stopwatch is started too soon. The compilation might not begin immediately

2023-01-25 12:24 UTC, acizmarik commented on src/Framework/Framework/Hosting/DotvvmPresenter.cs
> +                                                                        context.IsCommandExceptionHandled ? "Exception" :
```suggestion
                                                                        context.IsCommandExceptionHandled ? "HandledException" :
```

2023-01-25 12:24 UTC, acizmarik commented on src/Framework/Framework/Hosting/DotvvmPresenter.cs
> +                                                                    context.IsCommandExceptionHandled ? "Exception" :
```suggestion
                                                                    context.IsCommandExceptionHandled ? "HandledException" :
```

2023-02-08 10:18 UTC, exyi commented
I checked that the static command redirects work the same way as before (although I don't get it why :sweat_smile:). We have a test for it (`Redirect_StaticCommand`)

2023-02-08 12:01 UTC, acizmarik approved these changes
👍

2023-02-08 12:05 UTC, acizmarik requested changes
There are still some issues with assembly bindings to be solved.

2023-02-13 15:40 UTC, acizmarik approved these changes

2023-02-13 15:40 UTC, merged