Added support for string interpolation in bindings
riganti/dotvvm pull request #987
Opened 2021-04-01 14:49 UTC by acizmarik

Resolves #362. This PR adds support for string interpolation in bindings.

Interpolated strings are always translated into C# `String.Format(...)` calls, unless a constant string is provided with no interpolation expressions. When compiling `String.Format(...)` calls to JavaScript, the function `dotvvm.globalize.format(...)` is used.

Implementation progress:
- [x] Expression interpolation support
- [ ] String formatting component
- [ ] String alignment component

I am guessing that formatting component can be quite useful. However, I am not really sure whether we want to support string alignments. Any thoughts?

2021-04-02 13:23 UTC, exyi requested changes
Pretty cool :) Just please have a look at the case with nested expressions.

2021-04-02 13:23 UTC, exyi commented on src/DotVVM.Framework/Compilation/Binding/ExpressionBuildingVisitor.cs
> +                Target = Registry.Resolve(nameof(String))
```suggestion
                Target = typeof(string)
```

If you'd define your own string, we still want to use System.String (as C# does: https://sharplab.io/#v2:C4LglgNgNAJiDUAfAAgJgIwFgBQyDMABGgQMrABOYAdgOYEDeOBzRhy6ADAQLIAU1wAgA8AlAyYtJyAOwEAJACJ6QgL4KA3BOYqcKoA=)

2021-04-02 13:23 UTC, exyi commented on src/DotVVM.Framework/Compilation/Binding/ExpressionBuildingVisitor.cs
> +                }
```suggestion
                var arguments = node.Arguments.Select(arg => HandleErrors(node.Arguments[index], Visit))[.ToArray()];
```

;)

2021-04-02 13:23 UTC, exyi commented on src/DotVVM.Framework.Tests.Common/Binding/BindingCompilationTests.cs
> +        public void BindingCompiler_Valid_InterpolatedString_WithSimpleExpressions(string expression, string evaluated)
Could you please also test that nested string interpolations work? For example `$"{ string.Join(", ", MyArray) }"`, I think it may be broken now.

2021-04-02 13:23 UTC, exyi commented on src/DotVVM.Framework/Compilation/Parser/Binding/Parser/BindingParser.cs
> +            text = ParseStringLiteral(text, out error).Substring(1);
You are parsing it as a standard string literal while it may actually contain nested expressions which may also contain `"`.

2021-04-07 14:54 UTC, acizmarik commented
Thanks for review. You were right - nested expressions were broken if they contained strings. It should be fixed now. Also formatting should now be supported.
I will add more tests, do some refactoring and then will request one more review of the changes :)

2021-04-21 14:11 UTC, merged